---
# List of job stages
stages:
  - lint
  - test

# Lint the source files, need an image which includes rustfmt, the
# standard "rust:latest" does not.
lint:
  image: "guangie88/rustfmt-clippy"
  stage: lint
  script:
    - rustfmt --version
    - rustfmt src/lib.rs src/id3_display.rs

# Run cargo test
test:
  image: "rust:latest"
  stage: test
  script:
    - cargo --version
    - rustc --version
    - cargo test
